/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CustomFieldResponse;
import com.konfigthis.client.model.ProjectCompact;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CustomFieldSettingResponseAllOf
 */
public class CustomFieldSettingResponseAllOfTest {
    private final CustomFieldSettingResponseAllOf model = new CustomFieldSettingResponseAllOf();

    /**
     * Model tests for CustomFieldSettingResponseAllOf
     */
    @Test
    public void testCustomFieldSettingResponseAllOf() {
        // TODO: test CustomFieldSettingResponseAllOf
    }

    /**
     * Test the property 'project'
     */
    @Test
    public void projectTest() {
        // TODO: test project
    }

    /**
     * Test the property 'isImportant'
     */
    @Test
    public void isImportantTest() {
        // TODO: test isImportant
    }

    /**
     * Test the property 'parent'
     */
    @Test
    public void parentTest() {
        // TODO: test parent
    }

    /**
     * Test the property 'customField'
     */
    @Test
    public void customFieldTest() {
        // TODO: test customField
    }

}
