/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.UserCompact;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CustomFieldResponseAllOf
 */
public class CustomFieldResponseAllOfTest {
    private final CustomFieldResponseAllOf model = new CustomFieldResponseAllOf();

    /**
     * Model tests for CustomFieldResponseAllOf
     */
    @Test
    public void testCustomFieldResponseAllOf() {
        // TODO: test CustomFieldResponseAllOf
    }

    /**
     * Test the property 'representationType'
     */
    @Test
    public void representationTypeTest() {
        // TODO: test representationType
    }

    /**
     * Test the property 'idPrefix'
     */
    @Test
    public void idPrefixTest() {
        // TODO: test idPrefix
    }

    /**
     * Test the property 'isFormulaField'
     */
    @Test
    public void isFormulaFieldTest() {
        // TODO: test isFormulaField
    }

    /**
     * Test the property 'isValueReadOnly'
     */
    @Test
    public void isValueReadOnlyTest() {
        // TODO: test isValueReadOnly
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'peopleValue'
     */
    @Test
    public void peopleValueTest() {
        // TODO: test peopleValue
    }

}
