/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PortfolioCompact;
import com.konfigthis.client.model.UserCompact;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PortfolioMembershipCompactAllOf
 */
public class PortfolioMembershipCompactAllOfTest {
    private final PortfolioMembershipCompactAllOf model = new PortfolioMembershipCompactAllOf();

    /**
     * Model tests for PortfolioMembershipCompactAllOf
     */
    @Test
    public void testPortfolioMembershipCompactAllOf() {
        // TODO: test PortfolioMembershipCompactAllOf
    }

    /**
     * Test the property 'portfolio'
     */
    @Test
    public void portfolioTest() {
        // TODO: test portfolio
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

}
