/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.OrganizationExportRequest;
import com.konfigthis.client.model.OrganizationExportsCreateExportRequestRequest;
import com.konfigthis.client.model.OrganizationExportsCreateExportRequestResponse;
import com.konfigthis.client.model.OrganizationExportsGetExportDetailsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrganizationExportsApi
 */
@Disabled
public class OrganizationExportsApiTest {

    private static OrganizationExportsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new OrganizationExportsApi(apiClient);
    }

    /**
     * Create an organization export request
     *
     * This method creates a request to export an Organization. Asana will complete the export at some point after you create the request.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createExportRequestTest() throws ApiException {
        OrganizationExportRequest data = null;
        Boolean optPretty = null;
        List<String> optFields = null;
        OrganizationExportsCreateExportRequestResponse response = api.createExportRequest()
                .data(data)
                .optPretty(optPretty)
                .optFields(optFields)
                .execute();
        // TODO: test validations
    }

    /**
     * Get details on an org export request
     *
     * Returns details of a previously-requested Organization export.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getExportDetailsTest() throws ApiException {
        String organizationExportGid = null;
        Boolean optPretty = null;
        List<String> optFields = null;
        OrganizationExportsGetExportDetailsResponse response = api.getExportDetails(organizationExportGid)
                .optPretty(optPretty)
                .optFields(optFields)
                .execute();
        // TODO: test validations
    }

}
