/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.RuleTriggerRequest;
import com.konfigthis.client.model.RulesTriggerRuleRequestRequest;
import com.konfigthis.client.model.RulesTriggerRuleRequestResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RulesApi
 */
@Disabled
public class RulesApiTest {

    private static RulesApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new RulesApi(apiClient);
    }

    /**
     * Trigger a rule
     *
     * Trigger a rule which uses an [\&quot;incoming web request\&quot;](https://raw.githubusercontent.com) trigger.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void triggerRuleRequestTest() throws ApiException {
        String ruleTriggerGid = null;
        RuleTriggerRequest data = null;
        RulesTriggerRuleRequestResponse response = api.triggerRuleRequest(ruleTriggerGid)
                .data(data)
                .execute();
        // TODO: test validations
    }

}
