/*
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.WorkspaceMembershipsGetRecordByIdResponse;
import com.konfigthis.client.model.WorkspaceMembershipsGetUserMembershipsResponse;
import com.konfigthis.client.model.WorkspaceMembershipsListForWorkspaceResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WorkspaceMembershipsApi
 */
@Disabled
public class WorkspaceMembershipsApiTest {

    private static WorkspaceMembershipsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new WorkspaceMembershipsApi(apiClient);
    }

    /**
     * Get a workspace membership
     *
     * Returns the complete workspace record for a single workspace membership.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRecordByIdTest() throws ApiException {
        String workspaceMembershipGid = null;
        Boolean optPretty = null;
        List<String> optFields = null;
        WorkspaceMembershipsGetRecordByIdResponse response = api.getRecordById(workspaceMembershipGid)
                .optPretty(optPretty)
                .optFields(optFields)
                .execute();
        // TODO: test validations
    }

    /**
     * Get workspace memberships for a user
     *
     * Returns the compact workspace membership records for the user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUserMembershipsTest() throws ApiException {
        String userGid = null;
        Boolean optPretty = null;
        Integer limit = null;
        String offset = null;
        List<String> optFields = null;
        WorkspaceMembershipsGetUserMembershipsResponse response = api.getUserMemberships(userGid)
                .optPretty(optPretty)
                .limit(limit)
                .offset(offset)
                .optFields(optFields)
                .execute();
        // TODO: test validations
    }

    /**
     * Get the workspace memberships for a workspace
     *
     * Returns the compact workspace membership records for the workspace.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listForWorkspaceTest() throws ApiException {
        String workspaceGid = null;
        String user = null;
        Boolean optPretty = null;
        Integer limit = null;
        String offset = null;
        List<String> optFields = null;
        WorkspaceMembershipsListForWorkspaceResponse response = api.listForWorkspace(workspaceGid)
                .user(user)
                .optPretty(optPretty)
                .limit(limit)
                .offset(offset)
                .optFields(optFields)
                .execute();
        // TODO: test validations
    }

}
